# Generated by Django 4.2.4 on 2023-08-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='role',
        ),
    ]
