# Generated by Django 4.2.4 on 2023-08-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_candidate_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='transcription',
            field=models.TextField(null=True),
        ),
    ]
